import type { Department, Employee } from "@/lib/types";

export const demoDepartments: Department[] = [
  { id: "11111111-1111-4111-8111-111111111111", name: "Sản phẩm", description: "Biến ý tưởng thành trải nghiệm hữu ích." },
  { id: "22222222-2222-4222-8222-222222222222", name: "Kỹ thuật", description: "Xây nền tảng ổn định và dễ phát triển." },
  { id: "33333333-3333-4333-8333-333333333333", name: "Vận hành", description: "Giữ mọi thứ chạy trơn tru mỗi ngày." },
  { id: "44444444-4444-4444-8444-444444444444", name: "Con người", description: "Chăm sóc trải nghiệm của cả đội ngũ." },
  { id: "55555555-5555-4555-8555-555555555555", name: "Kinh doanh", description: "Kết nối sản phẩm với đúng khách hàng." },
];

export const demoEmployees: Employee[] = [
  {
    id: "a1111111-1111-4111-8111-111111111111",
    slug: "an-nguyen",
    fullName: "Nguyễn Minh An",
    initials: "MA",
    avatarUrl: null,
    email: "an.nguyen@example.com",
    jobTitle: "Product Designer",
    departmentId: demoDepartments[0].id,
    department: "Sản phẩm",
    location: "TP. Hồ Chí Minh",
    bio: "Mình thích biến những chuyện rối rắm thành trải nghiệm thật dễ hiểu. Luôn sẵn sàng cho một buổi brainstorm có đồ ăn.",
    interests: ["Cà phê", "Nhiếp ảnh", "Board game"],
    joinedDate: "2024-03-18",
    status: "active",
    role: "user",
    accent: "coral",
  },
  {
    id: "a2222222-2222-4222-8222-222222222222",
    slug: "linh-tran",
    fullName: "Trần Gia Linh",
    initials: "GL",
    avatarUrl: null,
    email: "linh.tran@example.com",
    jobTitle: "Frontend Engineer",
    departmentId: demoDepartments[1].id,
    department: "Kỹ thuật",
    location: "Đà Nẵng",
    bio: "Chuyên săn bug trước giờ ăn trưa. Cuối tuần thường có mặt ở một cung đường trekking nào đó.",
    interests: ["Trekking", "Mèo", "Web đẹp"],
    joinedDate: "2023-08-07",
    status: "active",
    role: "admin",
    accent: "mint",
  },
  {
    id: "a3333333-3333-4333-8333-333333333333",
    slug: "bao-le",
    fullName: "Lê Quốc Bảo",
    initials: "QB",
    avatarUrl: null,
    email: "bao.le@example.com",
    jobTitle: "Backend Engineer",
    departmentId: demoDepartments[1].id,
    department: "Kỹ thuật",
    location: "TP. Hồ Chí Minh",
    bio: "Thích hệ thống chạy êm, truy vấn chạy nhanh và những cuộc trò chuyện không cần slide.",
    interests: ["Chạy bộ", "Cà phê", "Cờ vua"],
    joinedDate: "2025-01-13",
    status: "active",
    role: "user",
    accent: "blue",
  },
  {
    id: "a4444444-4444-4444-8444-444444444444",
    slug: "vy-pham",
    fullName: "Phạm Thảo Vy",
    initials: "TV",
    avatarUrl: null,
    email: "vy.pham@example.com",
    jobTitle: "People Partner",
    departmentId: demoDepartments[3].id,
    department: "Con người",
    location: "TP. Hồ Chí Minh",
    bio: "Người bạn đồng hành của mọi người ở công ty. Nếu cần một người lắng nghe, cứ nhắn mình nhé.",
    interests: ["Yoga", "Đọc sách", "Nấu ăn"],
    joinedDate: "2022-11-21",
    status: "active",
    role: "moderator",
    accent: "rose",
  },
  {
    id: "a5555555-5555-4555-8555-555555555555",
    slug: "khoa-do",
    fullName: "Đỗ Anh Khoa",
    initials: "AK",
    avatarUrl: null,
    email: "khoa.do@example.com",
    jobTitle: "Account Executive",
    departmentId: demoDepartments[4].id,
    department: "Kinh doanh",
    location: "Hà Nội",
    bio: "Thích gặp người mới và kể những câu chuyện hay. Có thể nói về bóng đá cả buổi mà không biết mệt.",
    interests: ["Bóng đá", "Podcast", "Du lịch"],
    joinedDate: "2024-09-02",
    status: "active",
    role: "user",
    accent: "amber",
  },
  {
    id: "a6666666-6666-4666-8666-666666666666",
    slug: "nhi-ho",
    fullName: "Hồ Yến Nhi",
    initials: "YN",
    avatarUrl: null,
    email: "nhi.ho@example.com",
    jobTitle: "Operations Specialist",
    departmentId: demoDepartments[2].id,
    department: "Vận hành",
    location: "TP. Hồ Chí Minh",
    bio: "Mình thích checklist gọn gàng, cây xanh và những quán ăn ngon giấu trong hẻm nhỏ.",
    interests: ["Cây xanh", "Ẩm thực", "Phim ảnh"],
    joinedDate: "2025-05-26",
    status: "active",
    role: "user",
    accent: "violet",
  },
  {
    id: "a7777777-7777-4777-8777-777777777777",
    slug: "tuan-vo",
    fullName: "Võ Thanh Tuấn",
    initials: "TT",
    avatarUrl: null,
    email: "tuan.vo@example.com",
    jobTitle: "Product Manager",
    departmentId: demoDepartments[0].id,
    department: "Sản phẩm",
    location: "TP. Hồ Chí Minh",
    bio: "Hay hỏi “vì sao” và thích biến các cuộc thảo luận dài thành ba gạch đầu dòng rõ ràng.",
    interests: ["Đạp xe", "Board game", "Công nghệ"],
    joinedDate: "2021-06-14",
    status: "active",
    role: "user",
    accent: "mint",
  },
  {
    id: "a8888888-8888-4888-8888-888888888888",
    slug: "my-dang",
    fullName: "Đặng Hà My",
    initials: "HM",
    avatarUrl: null,
    email: "my.dang@example.com",
    jobTitle: "Content Executive",
    departmentId: demoDepartments[4].id,
    department: "Kinh doanh",
    location: "Hà Nội",
    bio: "Viết chữ, chụp hình và sưu tầm những mẩu chuyện nhỏ khiến một ngày bình thường trở nên đáng nhớ.",
    interests: ["Viết lách", "Nhiếp ảnh", "Âm nhạc"],
    joinedDate: "2025-08-11",
    status: "active",
    role: "user",
    accent: "coral",
  },
];
